=== TreasuredOwl/Syntax-Dev-server-/game/data/xsd/items.xsd
<?xml version="1.1" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="setType">
		<xs:attribute name="name" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="displayId" />
					<xs:enumeration value="agathion_energy" />
					<xs:enumeration value="armor_type" />
					<xs:enumeration value="attack_range" />
					<xs:enumeration value="auto_destroy_time" />
					<xs:enumeration value="blessed" />
					<xs:enumeration value="bodypart" />
					<xs:enumeration value="capsuled_items" />
					<xs:enumeration value="change_weaponId" />
					<xs:enumeration value="crystal_count" />
					<xs:enumeration value="crystal_type" />
					<xs:enumeration value="damage_range" />
					<xs:enumeration value="default_action" />
					<xs:enumeration value="duration" />
					<xs:enumeration value="element_enabled" />
					<xs:enumeration value="enchant_enabled" />
					<xs:enumeration value="enchant4_skill" />
					<xs:enumeration value="enchanted" />
					<xs:enumeration value="equip_condition" />
					<xs:enumeration value="equip_reuse_delay" />
					<xs:enumeration value="ex_immediate_effect" />
					<xs:enumeration value="etcitem_type" />
					<xs:enumeration value="for_npc" />
					<xs:enumeration value="handler" />
					<xs:enumeration value="icon" />
					<xs:enumeration value="immediate_effect" />
					<xs:enumeration value="is_depositable" />
					<xs:enumeration value="is_destroyable" />
					<xs:enumeration value="is_dropable" />
					<xs:enumeration value="is_freightable" />
					<xs:enumeration value="is_magic_weapon" />
					<xs:enumeration value="is_oly_restricted" />
					<xs:enumeration value="is_premium" />
					<xs:enumeration value="is_questitem" />
					<xs:enumeration value="is_sellable" />
					<xs:enumeration value="is_stackable" />
					<xs:enumeration value="is_tradable" />
					<xs:enumeration value="isAttackWeapon" />
					<xs:enumeration value="isForceEquip" />
					<xs:enumeration value="required_item" />
					<xs:enumeration value="item_skill" />
					<xs:enumeration value="allow_self_resurrection" />
					<xs:enumeration value="material" />
					<xs:enumeration value="mp_consume" />
					<xs:enumeration value="oncrit_chance" />
					<xs:enumeration value="oncrit_skill" />
					<xs:enumeration value="onmagic_chance" />
					<xs:enumeration value="onmagic_skill" />
					<xs:enumeration value="price" />
					<xs:enumeration value="random_damage" />
					<xs:enumeration value="recipe_id" />
					<xs:enumeration value="reduced_mp_consume" />
					<xs:enumeration value="reduced_soulshot" />
					<xs:enumeration value="reuse_delay" />
					<xs:enumeration value="shared_reuse_group" />
					<xs:enumeration value="soulshots" />
					<xs:enumeration value="spiritshots" />
					<xs:enumeration value="time" />
					<xs:enumeration value="unequip_skill" />
					<xs:enumeration value="use_condition" />
					<xs:enumeration value="useSkillDisTime" />
					<xs:enumeration value="useWeaponSkillsOnly" />
					<xs:enumeration value="weapon_type" />
					<xs:enumeration value="weight" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="val" type="xs:token" use="required" />
	</xs:complexType>
	<xs:complexType name="playerType">
		<xs:attribute name="castle">
			<xs:simpleType>
				<xs:restriction base="xs:integer">
					<xs:minInclusive value="-1" />
					<xs:maxInclusive value="9" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="clanHall" type="xs:normalizedString" />
		<xs:attribute name="class_id_restriction" type="xs:normalizedString" />
		<xs:attribute name="cloakStatus" type="xs:boolean" />
		<xs:attribute name="isHero" type="xs:boolean" />
		<xs:attribute name="isPvpFlagged" type="xs:boolean" />
		<xs:attribute name="insideZoneId" type="xs:normalizedString" />
		<xs:attribute name="level">
			<xs:simpleType>
				<xs:restriction base="xs:positiveInteger">
					<xs:minInclusive value="1" />
					<xs:maxInclusive value="85" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="pledgeClass">
			<xs:simpleType>
				<xs:restriction base="xs:integer">
					<xs:minInclusive value="-1" />
					<xs:maxInclusive value="11" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="levelRange" type="xs:token" />
		<xs:attribute name="races" type="xs:token" />
		<xs:attribute name="sex" type="xs:byte" use="optional" />
		<xs:attribute name="fort" type="xs:integer" fixed="-1" />
		<xs:attribute name="chaotic" type="xs:boolean" />
		<xs:attribute name="subclass" type="xs:boolean" />
		<xs:attribute name="SiegeZone" type="xs:positiveInteger" />
		<xs:attribute name="flyMounted" type="xs:boolean" />
		<xs:attribute name="instanceId" type="xs:normalizedString" />
		<xs:attribute name="categoryType" type="xs:normalizedString" />
		<xs:attribute name="pkCount" type="xs:int" />
		<xs:attribute name="vehicleMounted" type="xs:boolean" />
	</xs:complexType>
	<xs:complexType name="andType">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element name="using" type="usingType" />
			<xs:element name="player" type="playerType" />
			<xs:element name="target" type="targetType" />
			<xs:element name="not" type="notType" />
			<xs:element name="game" type="gameType" />
			<xs:element name="or" minOccurs="0" type="andType" />
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="gameType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="night" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="notType">
		<xs:sequence>
			<xs:element name="using" minOccurs="0" type="usingType" />
			<xs:element name="player" minOccurs="0" type="playerType" />
			<xs:element name="target" minOccurs="0" type="targetType" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="usingType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="kind" use="optional" />
				<xs:attribute type="xs:string" name="slot" use="optional" />
				<xs:attribute type="xs:string" name="weaponChange" use="optional" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="targetType">
		<xs:attribute name="levelRange" type="xs:token" />
		<xs:attribute name="categoryType" type="xs:normalizedString" />
	</xs:complexType>
	<xs:complexType name="enchantType">
		<xs:attribute name="order" type="xs:byte" use="optional" />
		<xs:attribute name="stat" use="required" type="statType" />
		<xs:attribute name="val" type="xs:integer" fixed="0" use="required" />
	</xs:complexType>
	<xs:simpleType name="statType">
		<xs:restriction base="xs:token">
			<xs:enumeration value="mAtk" />
			<xs:enumeration value="mDef" />
			<xs:enumeration value="pAtk" />
			<xs:enumeration value="pDef" />
			<xs:enumeration value="sDef" />
			<xs:enumeration value="mAtk" />
			<xs:enumeration value="pAtkAngle" />
			<xs:enumeration value="pAtkRange" />
			<xs:enumeration value="pAtkSpd" />
			<xs:enumeration value="critRate" />
			<xs:enumeration value="rShld" />
			<xs:enumeration value="rEvas" />
			<xs:enumeration value="accCombat" />
			<xs:enumeration value="darkRes" />
			<xs:enumeration value="earthRes" />
			<xs:enumeration value="fireRes" />
			<xs:enumeration value="holyPower" />
			<xs:enumeration value="holyRes" />
			<xs:enumeration value="maxMp" />
			<xs:enumeration value="waterRes" />
			<xs:enumeration value="windRes" />
			<xs:enumeration value="magicSuccRes" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="condType">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element name="using" type="usingType" />
			<xs:element name="and" type="andType" />
			<xs:element name="not" type="notType" />
			<xs:element name="player" type="playerType" />
			<xs:element name="target" type="targetType" />
		</xs:choice>
		<xs:attribute type="xs:short" name="msgId" use="optional" />
		<xs:attribute type="xs:byte" name="addName" use="optional" />
		<xs:attribute type="xs:string" name="msg" use="optional" />
	</xs:complexType>
	<xs:complexType name="addType">
		<xs:attribute name="order" type="xs:byte" use="optional" />
		<xs:attribute name="stat" type="statType" use="required" />
		<xs:attribute name="val" type="xs:decimal" use="required" />
	</xs:complexType>
	<xs:complexType name="forType" mixed="true">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element name="add" type="addType" />
			<xs:element name="mul" type="addType" />
			<xs:element name="sub" type="addType" />
			<xs:element name="basemul" type="addType" />
			<xs:element name="set" type="addType" />
			<xs:element name="enchant" maxOccurs="2" minOccurs="0" type="enchantType" />
		</xs:choice>
		<xs:attribute type="xs:string" name="name" use="optional" />
		<xs:attribute type="xs:byte" name="val" use="optional" />
	</xs:complexType>
	<xs:complexType name="itemType">
		<xs:sequence maxOccurs="1" minOccurs="1">
			<xs:element name="set" maxOccurs="unbounded" minOccurs="1" type="setType" />
			<xs:element name="conditions" maxOccurs="2" minOccurs="0" type="condType" />
			<xs:element name="stats" maxOccurs="1" minOccurs="0" type="forType" />
		</xs:sequence>
		<xs:attribute name="id" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:positiveInteger">
					<xs:minInclusive value="1" />
					<xs:maxInclusive value="65535" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="name" type="xs:normalizedString" use="required" />
		<xs:attribute name="type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="Armor" />
					<xs:enumeration value="EtcItem" />
					<xs:enumeration value="Weapon" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="item" type="itemType" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== TreasuredOwl/Syntax-Dev-server-/game/data/stats/items/20800-20899.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
	<item id="20800" type="EtcItem" name="Red Opera Agathion 7-Day Pack - Spear of Flames">
		<!-- Wrapped pack containing a Red Opera Agathion (7 day). Cannot be exchanged, dropped, or sold. Can be stored in a private warehouse. -->
		<set name="icon" val="BranchSys.icon.br_four_leaf_clover_box_i00" />
		<set name="default_action" val="PEEL" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="PAPER" />
		<set name="weight" val="100" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_depositable" val="false" />
		<set name="is_stackable" val="true" />
		<set name="is_premium" val="true" />
		<set name="is_freightable" val="true" />
		<set name="handler" val="ExtractableItems" />
		<set name="capsuled_items" val="20778,1,1,100" />
	</item>
	<item id="20801" type="EtcItem" name="Opera Agathion Pack">
		<!-- Wrapped pack containing an Opera Agathion. Cannot be exchanged, dropped, or sold. Can be stored in a private warehouse. -->
		<set name="icon" val="BranchSys.icon.br_four_leaf_clover_box_i00" />
		<set name="default_action" val="PEEL" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="PAPER" />
		<set name="weight" val="100" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_depositable" val="false" />
		<set name="is_stackable" val="true" />
		<set name="is_premium" val="true" />
		<set name="is_freightable" val="true" />
		<set name="handler" val="ExtractableItems" />
		<set name="capsuled_items" val="20779,1,1,100" />
	</item>
	<item id="20802" type="EtcItem" name="Opera Agathion 30-Day Pack - Sword of Life">
		<!-- Wrapped pack containing an Opera Agathion. Cannot be exchanged, dropped, or sold. Can be stored in a private warehouse. -->
		<set name="icon" val="BranchSys.icon.br_four_leaf_clover_box_i00" />
		<set name="default_action" val="PEEL" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="PAPER" />
		<set name="weight" val="100" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_depositable" val="false" />
		<set name="is_stackable" val="true" />
		<set name="is_premium" val="true" />
		<set name="is_freightable" val="true" />
		<set name="handler" val="ExtractableItems" />
		<set name="capsuled_items" val="20780,1,1,100" />
	</item>
	<item id="20803" type="EtcItem" name="Miss Chipao Agathion 7-Day Pack - Decrease Weight">
		<!-- Wrapped pack containing Miss Chipao Agathion (7 day). Cannot be exchanged, dropped, or sold. Can be stored in a private warehouse. -->
		<set name="icon" val="BranchSys.icon.br_four_leaf_clover_box_i00" />
		<set name="default_action" val="PEEL" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="PAPER" />
		<set name="weight" val="100" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_depositable" val="false" />
		<set name="is_stackable" val="true" />
		<set name="is_premium" val="true" />
		<set name="is_freightable" val="true" />
		<set name="handler" val="ExtractableItems" />
		<set name="capsuled_items" val="20781,1,1,100" />
	</item>
	<item id="20804" type="EtcItem" name="Nepal Snow Agathion Pack">
		<!-- Wrapped pack containing a Nepal Snow Agathion. Cannot be exchanged, dropped, or sold. Can be stored in a private warehouse. -->
		<set name="icon" val="BranchSys.icon.br_four_leaf_clover_box_i00" />
		<set name="default_action" val="PEEL" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="PAPER" />
		<set name="weight" val="100" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_depositable" val="false" />
		<set name="is_stackable" val="true" />
		<set name="is_premium" val="true" />
		<set name="is_freightable" val="true" />
		<set name="handler" val="ExtractableItems" />
		<set name="capsuled_items" val="20782,1,1,100" />
	</item>
	<item id="20805" type="EtcItem" name="Round Ball Snow Agathion Pack">
		<!-- Wrapped pack containing a Round Ball Snow Agathion. Cannot be exchanged, dropped, or sold. Can be stored in a private warehouse. -->
		<set name="icon" val="BranchSys.icon.br_four_leaf_clover_box_i00" />
		<set name="default_action" val="PEEL" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="PAPER" />
		<set name="weight" val="100" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_depositable" val="false" />
		<set name="is_stackable" val="true" />
		<set name="is_premium" val="true" />
		<set name="is_freightable" val="true" />
		<set name="handler" val="ExtractableItems" />
		<set name="capsuled_items" val="20783,1,1,100" />
	</item>
	<item id="20806" type="EtcItem" name="Ladder Snow Agathion Pack">
		<!-- Wrapped pack containing a Ladder Snow Agathion. Cannot be exchanged, dropped, or sold. Can be stored in a private warehouse. -->
		<set name="icon" val="BranchSys.icon.br_four_leaf_clover_box_i00" />
		<set name="default_action" val="PEEL" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="PAPER" />
		<set name="weight" val="100" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_depositable" val="false" />
		<set name="is_stackable" val="true" />
		<set name="is_premium" val="true" />
		<set name="is_freightable" val="true" />
		<set name="handler" val="ExtractableItems" />
		<set name="capsuled_items" val="20784,1,1,100" />
	</item>
	<item id="20807" type="EtcItem" name="Nepal Snow Agathion 7-Day Pack - Snow's Haste">
		<!-- Wrapped pack containing a Nepal Snow Agathion (7 day). Cannot be exchanged, dropped, or sold. Can be stored in a private warehouse. -->
		<set name="icon" val="BranchSys.icon.br_four_leaf_clover_box_i00" />
		<set name="default_action" val="PEEL" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="PAPER" />
		<set name="weight" val="100" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_depositable" val="false" />
		<set name="is_stackable" val="true" />
		<set name="is_premium" val="true" />
		<set name="is_freightable" val="true" />
		<set name="handler" val="ExtractableItems" />
		<set name="capsuled_items" val="20785,1,1,100" />
	</item>
	<item id="20808" type="EtcItem" name="Round Ball Snow Agathion 7-Day Pack - Snow's Acumen">
		<!-- Wrapped pack containing a Round Ball Snow Agathion (7 day). Cannot be exchanged, dropped, or sold. Can be stored in a private warehouse. -->
		<set name="icon" val="BranchSys.icon.br_four_leaf_clover_box_i00" />
		<set name="default_action" val="PEEL" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="PAPER" />
		<set name="weight" val="100" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_depositable" val="false" />
		<set name="is_stackable" val="true" />
		<set name="is_premium" val="true" />
		<set name="is_freightable" val="true" />
		<set name="handler" val="ExtractableItems" />
		<set name="capsuled_items" val="20786,1,1,100" />
	</item>
	<item id="20809" type="EtcItem" name="Ladder Snow Agathion 7-Day Pack - Snow's Wind Walk">
		<!-- Wrapped pack containing a Ladder Snow Agathion (7 day). Cannot be exchanged, dropped, or sold. Can be stored in a private warehouse. -->
		<set name="icon" val="BranchSys.icon.br_four_leaf_clover_box_i00" />
		<set name="default_action" val="PEEL" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="PAPER" />
		<set name="weight" val="100" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_depositable" val="false" />
		<set name="is_stackable" val="true" />
		<set name="is_premium" val="true" />
		<set name="is_freightable" val="true" />
		<set name="handler" val="ExtractableItems" />
		<set name="capsuled_items" val="20787,1,1,100" />
	</item>
	<item id="20810" type="EtcItem" name="Flame Box Pack">
		<!-- Wrapped pack containing a Flame Box. Cannot be exchanged, dropped, or sold. Can be stored in a private warehouse. -->
		<set name="icon" val="BranchSys.icon.br_four_leaf_clover_box_i00" />
		<set name="default_action" val="PEEL" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="PAPER" />
		<set name="weight" val="100" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_depositable" val="false" />
		<set name="is_stackable" val="true" />
		<set name="is_premium" val="true" />
		<set name="is_freightable" val="true" />
		<set name="handler" val="ExtractableItems" />
		<set name="capsuled_items" val="20788,1,1,100" />
	</item>
	<item id="20811" type="EtcItem" name="Rocket Gun Hat Pack - Continuous Fireworks">
		<!-- Wrapped pack containing a Rocket Gun Hat. Cannot be exchanged, dropped, or sold. Can be stored in a private warehouse. -->
		<set name="icon" val="BranchSys.icon.br_four_leaf_clover_box_i00" />
		<set name="default_action" val="PEEL" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="PAPER" />
		<set name="weight" val="100" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
